### ISSUE TITLE
Windows removable device path

### ISSUE THREAD

**Issue by jpwhiting** [balena-io-modules/etcher-sdk#134]
Are the scanner.exe and file-to-file.exe examples meant to be usable on windows? Scanner seems to report removable device information, but all drives are missing a devicePath element in the output. There's a device and raw element both of which are something like '\\\\.\\PhysicalDevice2' or similar, but if file-to-file.exe image.iso \\\\.\\PhysicalDevice2 is used a new file is created on c:\ instead of the iso being written to the removable media.

It seems that it should be possible to use some device path such as those listed here: https://www.silabs.com/community/interface/knowledge-base.entry.html/2013/11/21/windows_usb_devicep-aGxD to refer to the usb removable media, but that also seems to fail (and would require some way of looking up the device vid, pid, serial number, and guid which aren't in the scanner output either). Is it possible to get scanner to output a devicePath that can be used to write to with file-to-file example?

**Comment by arnaudr-ccu** [comment]
I'm having the same issue, I don't know how to use the output of `scanner.exe` on Windows. `scanner.exe` always outputs `devicePath: null`. The closest thing to a path in the JSON output is, well, `path: \\\\.\\PhysicalDrive1`.

However that doesn't work with `multi-destination.exe`:

```
> multi-destination.exe SOME-IMAGE.img.zip '\\\\.\\PhysicalDrive`
error Error: At least one destination is required
```

**Comment by zvin** [comment]
@jpwhiting @arnaudr-ccu
`devicePath` only exists on Linux and looks like `/dev/disk/by-path/whatever`.
Use `device`, which exists on all platforms.

@jpwhiting
Depending on your shell, you may need to escape the anti-slashes: `\\\\.\\PhysicalDrive2` instead of `\\.\PhysicalDrive2`.
Use `multi-destination.ts` instead of `file-to-file.ts` as file-to-file won't work for writing on a block device in the latest version of the sdk.

>It seems that it should be possible to use some device path such as those listed here: https://www.silabs.com/community/interface/knowledge-base.entry.html/2013/11/21/windows_usb_devicep-aGxD to refer to the usb removable media

This is not supported and would need to be added to https://github.com/balena-io-modules/drivelist first

@arnaudr-ccu
The `multi-destination.ts` example has been updated to use `drive.device` instead of `drive.devicePath` and should now work on WIndows too.
